### ISSUE TITLE
request: jq + yj added to images

### ISSUE THREAD

**Issue by drnic** [heroku/pack-images#19]
I've been writing my CNBs in shell, rather than go, and need `jq` and `yj` in order to read/extract data from TOML files (e.g. a buildpack's own `buildpack.toml`). I tried my buildpack on `heroku-18` images but it failed as these two CLIs are missing. Could they be added in future?

* https://stedolan.github.io/jq/
* https://github.com/sclevine/yj/releases

Example CNB that uses jq/yj:

* https://github.com/starkandwayne/redis-cnb/
* https://github.com/starkandwayne/redis-cnb/blob/master/examples/builder-heroku18-fails.toml

**Comment by jqian2017** [comment]
+1 on wanting `jq` to be part of the `heroku-18` image... as I'm also writing CNB in shell... would love to use `jq` to do some detection in package.json

**Comment by edmorley** [comment]
Hi - sorry there being no reply sooner!

jq was added to the stack images (on which these images are based) back in:
https://github.com/heroku/stack-images/pull/174

For yj, it's not available via Ubuntu's APT repo and we try to avoid adding manual installations to our stack images, since they require more work to keep up to date amongst other issues (eg security).

In addition, whilst we heavily used bash for Heroku's classic (non-CNB) buildpacks, the additional complexity/surface area of CNBs (eg: size of [the buildpack spec](https://github.com/buildpacks/spec/blob/main/buildpack.md), needing to parse/manipulate TOML table arrays to process a build plan etc) makes the already-painful situation with bash even worse. 

As such we're instead using [libcnb.rs](https://github.com/heroku/libcnb.rs) (a new framework we have created for writing CNBs in Rust), so don't have a need for jq or yq longer term ourselves any more. 

For now if you want to use bash with more complex CNBs (that need caching or the build plan, so have to read TOML not just write it), you'll need to vendor [yj](https://github.com/sclevine/yj) (or [yq](https://github.com/mikefarah/yq)). 

An example of doing that can be found here (this repo's conversion to `libcnb.rs` is underway, however there are a few bash buildpacks left at present):
https://github.com/heroku/buildpacks-nodejs/blob/9fd5c0d9c91f09676216c81b6dc86eb49664cf52/buildpacks/npm/lib/build.sh#L52-L70

Closing since jq has been added already, and it's unlikely we'll install something outside of the Ubuntu APT repo.
